name: Deploy GitHub Pages from web folder

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 5 * * *'  # 5 AM UTC daily

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Copy /web to root of gh-pages
        run: |
          mkdir ../gh-pages
          cp -R web/* ../gh-pages/
          cd ../gh-pages
          git init
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Deploy to gh-pages"
          git branch -M gh-pages
          git remote add origin https://github.com/${{ github.repository }}.git
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gh-pages


