name: Generate Family Descriptions

on:
  workflow_dispatch:   # So you can trigger this manually on GitHub

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        pip install requests js2py

    - name: Install Requests
      run: pip install requests

    - name: Run generate_family_descriptions.py
      run: python generate_family_descriptions.py

    - name: Commit and Push updated files
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add web/data.js web/familyDescriptions.js
        git commit -m "Update data.js and familyDescriptions.js" || echo "No changes to commit"
        git push
